apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-churn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-churn
  template:
    metadata:
      labels:
        app: user-churn
    spec:
      containers:
      - name: user-churn
        image: us-central1-docker.pkg.dev/ayoba-183a7/gcf-artifacts/user-churn-test-deploy:latest
        ports:
        - containerPort: 5009
